spring:
  application:
    name: uaa
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
server:
  port: 7070

jwt:
  certificate:
    store:
      file: classpath:/certificate.jks
      password: scd1234
    key:
      alias: scd
      password: scd1234