server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: hello-service
security:
  oauth2:
    client:
      id: clientId
      client-secret: clientSecret
      scope: openid
      access-token-uri: http://localhost:7070/oauth/token
      user-authorization-uri: http://localhost:7070/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:7070/oauth/token_key